# Generated by Django 2.1.7 on 2019-04-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_updated', models.DateTimeField()),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('beer', models.CharField(max_length=200, null=True)),
                ('wine_glass', models.CharField(max_length=200, null=True)),
                ('wine_bottle', models.CharField(max_length=200, null=True)),
                ('well', models.CharField(max_length=200, null=True)),
                ('shot_beer', models.CharField(max_length=200, null=True)),
                ('display_notes', models.CharField(max_length=200, null=True)),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('time_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'happyhour',
            },
        ),
        migrations.CreateModel(
            name='HappyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('cross', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=75, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('price_level', models.IntegerField(null=True)),
                ('google_place_id', models.CharField(max_length=50, null=True)),
                ('time_updated', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'happyplace',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_updated', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='site.City')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'neighborhood',
            },
        ),
        migrations.AddField(
            model_name='happyplace',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='happy_places', to='site.Neighborhood'),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='happy_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='site.HappyPlace'),
        ),
    ]
