# Generated by Django 2.1.7 on 2019-04-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPlaces', '0002_auto_20190429_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyplace',
            name='google_place_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
