# Generated by Django 2.1.7 on 2019-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPlaces', '0003_auto_20190429_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happyhour',
            name='display_notes',
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
