stages:
  - before
  - main

zip:
  stage: before
  script:
    - zip ./* output.zip

push:
  stage: main
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp output.zip s3://owensx-bucket