stages:
  - before
  - main

zip:
  stage: before
  before_script:
    - apt-get update
    - apt-get install zip
  script:
    - zip -r target.zip ./*

push:
  stage: main
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp output.zip s3://owensx-bucket