# Generated by Django 2.1.7 on 2019-03-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeUpdated', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeUpdated', models.DateTimeField()),
                ('notes', models.CharField(max_length=200)),
                ('days', models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('Y', 'Saturday')], max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('beer', models.CharField(max_length=200, null=True)),
                ('wine_glass', models.CharField(max_length=200, null=True)),
                ('wine_bottle', models.CharField(max_length=200, null=True)),
                ('well', models.CharField(max_length=200, null=True)),
                ('shot_beer', models.CharField(max_length=200, null=True)),
                ('display_notes', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'happyhour',
            },
        ),
        migrations.CreateModel(
            name='HappyPlace',
            fields=[
                ('place_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id', models.IntegerField(unique=True)),
                ('timeUpdated', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('cross', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=75, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('price_level', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('googled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'happyplace',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeUpdated', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborhoods', to='site.City')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'neighborhood',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(max_length=200)),
                ('lastRun', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeUpdated', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('offset', models.IntegerField(choices=[('-8', 'Pacific'), ('-7', 'Mountain'), ('-6', 'Central'), ('-5', 'Eastern')])),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='happyplace',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='happyPlaces', to='site.Neighborhood'),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='happyPlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='happyHours', to='site.HappyPlace', to_field='id'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='site.State'),
        ),
    ]
