# Generated by Django 2.1.7 on 2019-04-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='beer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='shot_beer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='well',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='wine_bottle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='wine_glass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='happyplace',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
