# Generated by Django 2.1.7 on 2020-04-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_happyplace_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='happyplace',
            old_name='instagram',
            new_name='instagram_url',
        ),
    ]
