# Generated by Django 2.1.7 on 2020-07-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0006_auto_20200429_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='happyplace',
            old_name='instagram_url',
            new_name='instagram_handle',
        ),
    ]
